### PR TITLE
feat(ci.yml): Add checks for baremetal (RUN_LINUX=0).

### PR DESCRIPTION
**Pull request by arturum1**
Not sure if it should run in the FPGAs with both RUN_LINUX=0 and RUN_LINUX=1. For now, both checks are run in the FPGAs.

### CODE REVIEW

**Comment by PedroAntunes178** [comment]
The CLINT and PLIC do not work with pc-emul. Therefor, the test does not work.

**Comment by jjts** [comment]
> The CLINT and PLIC do not work with pc-emul. Therefor, the test does not work.

Remove that test then

**Comment by arturum1** [comment]
> > The CLINT and PLIC do not work with pc-emul. Therefor, the test does not work.
> 
> Remove that test then

Removed in commit d231cc3

**Comment by jjts** [comment]
Other checks still fail

**Comment by arturum1** [comment]
The other checks fail due to issues with Linux (RUN_LINUX=1). I'm not sure how to fix them at the moment.
The purpose of this PR was to add checks for RUN_LINUX=0.
The other checks were already failing before this PR.

**Pull request merged**
