### PR TITLE
Adapt makehex.py; Run OpenSBI; Update VexRiscv;

### PR DESCRIPTION
**Pull request by PedroAntunes178**
Adapt makehex.py in order to load more than 1 file in the memory on simulation;
Runs OpenSBI, but not the kenel;
Update VexRiscv in order to be able to run OpenSBI, had to use cached plugins and edit the misa CSR;

### CODE REVIEW

**Review by jjts — COMMENTED** [review]
Why change console only here?

**Comment by PedroAntunes178** [comment]
> Why change console only here?

We will move the console from iob-soc to iob-lib, then we'll merge iob-soc into iob-soc-vexriscv and update iob-soc-vexriscv LIB submodule.
After that, this PR could be accepted.

**Comment by jjts** [comment]
Why are checks failing? Could you fix them?

**Comment by jjts** [comment]
checks are still failing

**Comment by PedroAntunes178** [comment]
> checks are still failing

There are multiple reasons that are causing the checks to fail.
First, the files `test.expected` have the expected results for the original iob-soc.
Second, even if the `test.expected` content is changed, the CLINT timer value which is returned and printed varies 1 unit in some simulations.
The solution to these two first problems would be to use the same default firmware as iob-soc. But then we would not be testing the CLINT hardware.
Lastly, pc-emul does not work since the uart16550 and the clint submodule do not make use of mkregs.py; A simple workaround could be developed. But I think it would be more interesting if the submodules used mkregs to work with pc-emul.

**Comment by P-Miranda** [comment]
You can also change the github actions workflow to perform tests related to this specific repository.
Just add the tests that are relevant to this repository and that you already manually run when you want to check if everything is working.
You just need to edit the `.github/workflows/ci.yml` file. Let me know if you need help with that.
For example, you don't need to run test of fpga if is not supposed to run or not supported yet. 
Nor you need to compare against the `test.expected` files if your tests output something different.

**Comment by PedroAntunes178** [comment]
> You can also change the github actions workflow to perform tests related to this specific repository. Just add the tests that are relevant to this repository and that you already manually run when you want to check if everything is working. You just need to edit the `.github/workflows/ci.yml` file. Let me know if you need help with that. For example, you don't need to run test of fpga if is not supposed to run or not supported yet. Nor you need to compare against the `test.expected` files if your tests output something different.

Oki, Thank you!

**Pull request merged**
